version: "3.7"

networks:
  default:
    external: true
    name: aline

services:
  user-service:
    build: .
    image: aline/user-microservice
    restart: always
    env_file:
      - .env
    ports:
      - 8070:${APP_PORT}
